version: 2

builds:
  - id: justmount
    main: ./main.go
    binary: justmount
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

dockers_v2:
  - id: justmount
    dockerfile: Dockerfile.goreleaser
    ids:
      - justmount
    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/justmount"
    tags:
      - "{{ .Tag }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64

before:
  hooks:
    - rm -rf /tmp/justmount-helm
    - mkdir -p /tmp/justmount-helm
    - .github/scripts/helm-package-push.sh {{ .Version }} {{ .Tag }}

release:
  draft: false
