---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: justmount
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: justmount
  template:
    metadata:
      labels:
        app: justmount
    spec:
      containers:
        - name: justmount-csi-driver
          image: joejulian/csi-justmount:latest
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: CSI_ENDPOINT
              value: "unix:///var/lib/kubelet/plugins/justmount/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/justmount/
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/justmount/
            type: DirectoryOrCreate
        - name: mountpoint-dif
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
