name: Renovate

on:
  schedule:
    - cron: "19 7 * * *"
  workflow_dispatch:

concurrency:
  group: renovate-${{ github.repository }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.8
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
